version: "3.7"

services:
    sql-server-alodoutor:
        container_name: sql-server
        image: mcr.microsoft.com/mssql/server:2022-latest
        restart: always
        ports:
          - "1435:1433"
        environment:
            MSSQL_SA_PASSWORD: "P@ssw0rd"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"
        networks:
          - alo-doutor-net

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.13-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
            - "15672:15672"     
        networks:
          - alo-doutor-net

    identidade-api:
        container_name: identidade
        image: fiappostech/identidade
        build: 
            context: .
            dockerfile: ./Dockerfile.Identidade
        restart: always
        ports:
            - "9090:80"
        environment:
            aspnetcore_environment: Staging      
        depends_on:
            - sql-server-alodoutor        
        networks:
            - "alo-doutor-net"

    alodoutor-api:
        container_name: alodoutor
        image: fiappostech/alodoutor
        build:
            context: .
            dockerfile: ./Dockerfile.AloDoutor
        restart: always
        ports:
            - "9091:80"
        environment:
            aspnetcore_environment: Staging      
        depends_on:
            - sql-server-alodoutor
            - rabbitmq 
            - identidade-api
        networks:
            - "alo-doutor-net"

    alofinances-api:
        container_name: alofinances
        image: fiappostech/alofinances
        build:
            context: .
            dockerfile: ./Dockerfile.AloFinances
        restart: always
        ports:
            - "9092:80"
        environment:
            aspnetcore_environment: Staging      
        depends_on:
            - sql-server-alodoutor
            - rabbitmq
        networks:
            - alo-doutor-net 
  
networks:
  alo-doutor-net:
    driver: bridge
